# Generated by Django 3.2.5 on 2021-07-21 10:41

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, default='Happy to code. Share since its caring', max_length=500)),
                ('photo', cloudinary.models.CloudinaryField(default='profile.jpg', max_length=255, verbose_name='photo')),
                ('name', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='flashCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', tinymce.models.HTMLField(default='write a description', max_length=500)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('image_landing', cloudinary.models.CloudinaryField(max_length=255)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flash.profile')),
            ],
        ),
    ]
